# Generated by Django 6.0.4 on 2026-04-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_about_me_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shop_name',
            field=models.CharField(default='نام قروشگاه', max_length=255),
        ),
    ]
