# Generated by Django 6.0.4 on 2026-04-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shop_website_address',
            field=models.URLField(default='آدرس وبسایت فروشگاه', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shop_name',
            field=models.CharField(default='نام فروشگاه', max_length=255),
        ),
    ]
