# Generated by Django 6.0.4 on 2026-06-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_phone_as_username_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="num_available_sms",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of SMS credits available. Set manually via admin.",
            ),
        ),
    ]
