# Generated by Django 6.0.4 on 2026-07-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_profile_picture_and_business_domain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="shop_website_address",
        ),
    ]
