# Generated by Django 6.0.4 on 2026-08-12 16:49

import billing.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0053_supabaseorder_supabaseorderitem_supabaseuser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_id",
                    models.CharField(
                        default=billing.models.generate_billing_id,
                        editable=False,
                        max_length=48,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Billing ID must contain exactly 48 Latin letters and numbers, including at least one of each.",
                                regex="^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z0-9]{48}$",
                            )
                        ],
                    ),
                ),
                (
                    "sms_unit_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("400"),
                        editable=False,
                        max_digits=20,
                    ),
                ),
                (
                    "sms_count",
                    models.PositiveIntegerField(
                        choices=[
                            (1000, "1,000"),
                            (5000, "5,000"),
                            (25000, "25,000"),
                            (60000, "60,000"),
                            (150000, "150,000"),
                            (300000, "300,000"),
                            (500000, "500,000"),
                        ]
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=5,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=20,
                    ),
                ),
                (
                    "actual_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=20,
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("paid", "Paid")],
                        default="pending",
                        max_length=7,
                    ),
                ),
                (
                    "card_number",
                    models.CharField(default="5029081043096987", max_length=16),
                ),
                ("bale_id", models.CharField(default="@Retano_Admin", max_length=64)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"],
                        name="billing_bil_tenant__af2188_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("actual_price", Decimal("400000")),
                                ("discount_amount", Decimal("0")),
                                ("discount_percentage", Decimal("0.00")),
                                ("final_price", Decimal("400000")),
                                ("sms_count", 1000),
                                ("sms_unit_price", Decimal("400")),
                            ),
                            models.Q(
                                ("actual_price", Decimal("2000000")),
                                ("discount_amount", Decimal("100000")),
                                ("discount_percentage", Decimal("5.00")),
                                ("final_price", Decimal("1900000")),
                                ("sms_count", 5000),
                                ("sms_unit_price", Decimal("400")),
                            ),
                            models.Q(
                                ("actual_price", Decimal("10000000")),
                                ("discount_amount", Decimal("1000000")),
                                ("discount_percentage", Decimal("10.00")),
                                ("final_price", Decimal("9000000")),
                                ("sms_count", 25000),
                                ("sms_unit_price", Decimal("400")),
                            ),
                            models.Q(
                                ("actual_price", Decimal("24000000")),
                                ("discount_amount", Decimal("3600000")),
                                ("discount_percentage", Decimal("15.00")),
                                ("final_price", Decimal("20400000")),
                                ("sms_count", 60000),
                                ("sms_unit_price", Decimal("400")),
                            ),
                            models.Q(
                                ("actual_price", Decimal("60000000")),
                                ("discount_amount", Decimal("12000000")),
                                ("discount_percentage", Decimal("20.00")),
                                ("final_price", Decimal("48000000")),
                                ("sms_count", 150000),
                                ("sms_unit_price", Decimal("400")),
                            ),
                            models.Q(
                                ("actual_price", Decimal("120000000")),
                                ("discount_amount", Decimal("36000000")),
                                ("discount_percentage", Decimal("30.00")),
                                ("final_price", Decimal("84000000")),
                                ("sms_count", 300000),
                                ("sms_unit_price", Decimal("400")),
                            ),
                            models.Q(
                                ("actual_price", Decimal("200000000")),
                                ("discount_amount", Decimal("80000000")),
                                ("discount_percentage", Decimal("40.00")),
                                ("final_price", Decimal("120000000")),
                                ("sms_count", 500000),
                                ("sms_unit_price", Decimal("400")),
                            ),
                            _connector="OR",
                        ),
                        name="bill_valid_package_pricing",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["pending", "paid"])),
                        name="bill_valid_status",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("tenant",),
                        name="bill_one_pending_per_tenant",
                    ),
                ],
            },
        ),
    ]
