# Generated by Django 5.2.11 on 2026-02-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_unnormalizeddata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unnormalizeddata",
            name="RetanoClientID",
        ),
    ]
