# Generated by Django 5.2.11 on 2026-02-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_unnormalizeddata_retanoclientid"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="products_file",
            field=models.FileField(
                blank=True, null=True, upload_to="campaign_customers/"
            ),
        ),
        migrations.AddField(
            model_name="unnormalizeddata",
            name="product_link",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
