# Generated by Django 5.2.11 on 2026-02-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_campaign_products_file_unnormalizeddata_product_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="tenant_id",
            field=models.IntegerField(unique=True),
        ),
    ]
