# Generated by Django 5.2.11 on 2026-02-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_campaign_tenant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="unnormalizeddata",
            name="tenant_id",
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="tenant_id",
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
