# Generated by Django 5.2.11 on 2026-02-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_unnormalizeddata_tenant_id_alter_campaign_tenant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="b2c",
            field=models.CharField(
                choices=[
                    ("هیچ کدام", "هیچ کدام"),
                    ("SMS.ir", "SMS.ir"),
                    ("مدیانا", "مدیانا"),
                    ("کاوه نگار", "کاوه نگار"),
                    ("make.com", "make.com"),
                ],
                default="هیچ کدام",
                max_length=20,
            ),
        ),
    ]
