# Generated by Django 5.2.11 on 2026-02-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_campaign_b2c"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unnormalizeddata",
            name="product_link",
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
