# Generated by Django 6.0.4 on 2026-04-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_unnormalizeddata_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unnormalizeddata',
            name='user_id',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
