# Generated by Django 6.0.4 on 2026-04-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_unnormalizeddata_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='unnormalizeddata',
            name='internal_id',
            field=models.TextField(default='null'),
        ),
    ]
