# Generated by Django 6.0.4 on 2026-04-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_unnormalizeddata_internal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unnormalizeddata',
            name='user_id',
            field=models.IntegerField(editable=False),
        ),
    ]
