# Generated by Django 6.0.4 on 2026-04-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_unnormalizeddata_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='unnormalizeddata',
            name='column_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Maps original column names to our field names'),
        ),
    ]
