# Generated by Django 6.0.4 on 2026-04-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_unnormalizeddata_column_mapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='b2c',
        ),
        migrations.AddField(
            model_name='unnormalizeddata',
            name='internal_order_id',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='unnormalizeddata',
            name='internal_product_id',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='unnormalizeddata',
            name='order_id',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='unnormalizeddata',
            name='product_id',
            field=models.IntegerField(editable=False),
        ),
    ]
