# Generated by Django 6.0.4 on 2026-04-16 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_campaign_b2c_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers_mapping', models.JSONField(default=dict, help_text="مثال: {'internal_id': 0, 'first_name': 1, ...}")),
                ('products_mapping', models.JSONField(default=dict, help_text="مثال: {'internal_product_id': 0, 'product_name': 1, ...}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='column_mapping', to='core.campaign')),
            ],
        ),
    ]
