# Generated by Django 6.0.4 on 2026-04-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_campaigncolumnmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='product_source',
            field=models.CharField(choices=[('اولین محصول پرفروش', 'اولین محصول پرفروش'), ('دومین محصول پرفروش', 'دومین محصول پرفروش'), ('سومین محصول پرفروش', 'سومین محصول پرفروش'), ('پرتکرارترین محصول خریداری شده کاربر', 'پرتکرارترین محصول خریداری شده کاربر'), ('هیچ کدام', 'هیچ کدام')], default='اولین محصول پرفروش', max_length=100),
        ),
    ]
