# Generated by Django 6.0.4 on 2026-04-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_campaign_product_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='week',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='message_pattern',
            field=models.TextField(default='الگوی پیام'),
        ),
    ]
