# Generated by Django 6.0.4 on 2026-04-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_campaign_week_campaign_campaign_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='activation_base',
            field=models.CharField(choices=[('همیشه', 'همیشه'), ('آخرین خرید', 'آخرین خرید'), ('اولین خرید', 'اولین خرید'), ('یادآوری خرید بعدی', 'یادآوری خرید بعدی')], default='همیشه', max_length=50),
        ),
    ]
