# Generated by Django 6.0.4 on 2026-04-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_campaign_activation_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='buying_power',
            field=models.CharField(choices=[('خیلی بالا', 'خیلی بالا'), ('بالا', 'بالا'), ('متوسط', 'متوسط'), ('پایین', 'پایین'), ('خیلی پایین', 'خیلی پایین')], default='متوسط', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='activation_base',
            field=models.CharField(choices=[('همیشه', 'همیشه'), ('آخرین خرید', 'آخرین خرید'), ('اولین خرید', 'اولین خرید'), ('یادآوری خرید بعدی', 'یادآوری خرید بعدی'), ('قدرت خرید', 'قدرت خرید')], default='همیشه', max_length=50),
        ),
    ]
