# Generated by Django 6.0.4 on 2026-04-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_campaign_buying_power_alter_campaign_activation_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='buying_power',
            field=models.CharField(choices=[('همه', 'همه'), ('خیلی بالا', 'خیلی بالا'), ('بالا', 'بالا'), ('متوسط', 'متوسط'), ('پایین', 'پایین'), ('خیلی پایین', 'خیلی پایین')], default='همه', max_length=20),
        ),
    ]
