# Generated by Django 6.0.4 on 2026-05-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_campaign_buying_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='activation_base',
            field=models.CharField(blank=True, choices=[('همیشه', 'همیشه'), ('آخرین خرید', 'آخرین خرید'), ('اولین خرید', 'اولین خرید'), ('یادآوری خرید بعدی', 'یادآوری خرید بعدی'), ('قدرت خرید', 'قدرت خرید')], default='همیشه', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='comparison_type',
            field=models.CharField(blank=True, choices=[('بزرگتر از', 'بزرگتر از'), ('کوچکتر از', 'کوچکتر از'), ('برابر با', 'برابر با')], default='بزرگتر از', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='comparison_value',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (120, 120), (200, 200), (400, 400)], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='value_unit',
            field=models.CharField(blank=True, choices=[('روز', 'روز'), ('تومان', 'تومان')], default='روز', max_length=50, null=True),
        ),
    ]
