# Generated by Django 6.0.4 on 2026-05-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_campaign_activation_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='send_sms_time',
            field=models.TimeField(default='11:00:00'),
        ),
    ]
