# Generated by Django 6.0.4 on 2026-05-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_coupon_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='coupons_file',
            field=models.FileField(blank=True, null=True, upload_to='campaign_coupons'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='products_file',
            field=models.FileField(blank=True, null=True, upload_to='campaign_products/'),
        ),
        migrations.AlterField(
            model_name='unnormalizeddata',
            name='column_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Mapping original column names to our field names'),
        ),
    ]
