# Generated by Django 6.0.4 on 2026-05-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_campaign_coupons_file_alter_campaign_products_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='coupons_file',
            field=models.FileField(blank=True, null=True, upload_to='campaign_coupons/'),
        ),
    ]
