# Generated by Django 6.0.4 on 2026-05-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_coupon_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='comparison_value',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
