# Generated by Django 6.0.4 on 2026-05-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_campaign_coupon_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncolumnmapping',
            name='coupons_mapping',
            field=models.JSONField(default=dict, help_text="مثال: {'coupon_code': 0, 'discount_percentage': 1}"),
        ),
    ]
