# Generated by Django 6.0.4 on 2026-05-09 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_campaigncolumnmapping_coupons_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('coupon', 'Coupon'), ('sms', 'SMS'), ('campaign', 'Campaign'), ('trigger', 'Trigger'), ('system', 'System'), ('other', 'Other')], default='other', help_text='Which part of the system raised this error', max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='error', help_text='How severe is this error', max_length=20)),
                ('error_code', models.CharField(blank=True, help_text='A short machine-readable error code e.g. NO_COUPON_FOUND', max_length=100, null=True)),
                ('message', models.TextField(help_text='Human-readable error message')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Any extra structured data relevant to this error (campaign_id, user_id, etc.)')),
                ('resolved', models.BooleanField(default=False, help_text='Whether this error has been acknowledged and resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.ForeignKey(blank=True, help_text='The tenant this error belongs to, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id'], name='core_errorl_tenant__72e765_idx'), models.Index(fields=['source'], name='core_errorl_source_d2bc84_idx'), models.Index(fields=['severity'], name='core_errorl_severit_caf194_idx'), models.Index(fields=['resolved'], name='core_errorl_resolve_517393_idx'), models.Index(fields=['created_at'], name='core_errorl_created_a81460_idx')],
            },
        ),
    ]
