# Generated by Django 6.0.4 on 2026-05-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='unnormalizeddata',
            name='hair_type',
            field=models.CharField(default='oily', max_length=10),
        ),
        migrations.AddField(
            model_name='unnormalizeddata',
            name='skin_type',
            field=models.CharField(default='oily', max_length=10),
        ),
        migrations.AlterField(
            model_name='unnormalizeddata',
            name='gender',
            field=models.CharField(default='male', max_length=20),
        ),
    ]
