# Generated by Django 6.0.4 on 2026-05-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_unnormalizeddata_hair_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unnormalizeddata',
            name='hair_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unnormalizeddata',
            name='skin_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
