# Generated by Django 6.0.4 on 2026-05-12 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_unnormalizeddata_hair_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='tenant_id',
            new_name='tenant',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='tenant_id',
            new_name='tenant',
        ),
        migrations.RenameField(
            model_name='errorlog',
            old_name='tenant_id',
            new_name='tenant',
        ),
        migrations.RenameField(
            model_name='unnormalizeddata',
            old_name='tenant_id',
            new_name='tenant',
        ),
        migrations.RenameIndex(
            model_name='campaign',
            new_name='core_campai_tenant__ca24ce_idx',
            old_name='core_campai_tenant__85598d_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='core_errorl_tenant__8df847_idx',
            old_name='core_errorl_tenant__72e765_idx',
        ),
    ]
