# Generated by Django 6.0.4 on 2026-05-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_rename_tenant_id_campaign_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unnormalizeddata',
            name='hair_type',
        ),
        migrations.RemoveField(
            model_name='unnormalizeddata',
            name='skin_type',
        ),
    ]
