# Generated by Django 6.0.4 on 2026-05-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_unnormalizeddata_hair_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.TextField(max_length=2000, unique=True),
        ),
    ]
