# Generated by Django 6.0.4 on 2026-05-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rename_owner_id_tenant_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unnormalizeddata',
            name='TAG',
        ),
        migrations.AddField(
            model_name='unnormalizeddata',
            name='tag',
            field=models.CharField(blank=True, db_column='tag', max_length=100, null=True),
        ),
    ]
