# Generated by Django 6.0.4 on 2026-05-18 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_unnormalizeddata_tag_unnormalizeddata_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='coupons_file',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='customers_file',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='products_file',
        ),
        migrations.RemoveField(
            model_name='campaigncolumnmapping',
            name='campaign',
        ),
        migrations.CreateModel(
            name='TenantFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers_file', models.FileField(blank=True, null=True, upload_to='campaign_customers/')),
                ('products_file', models.FileField(blank=True, null=True, upload_to='campaign_products/')),
                ('coupons_file', models.FileField(blank=True, null=True, upload_to='campaign_coupons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='campaigncolumnmapping',
            name='upload',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='column_mapping', to='core.tenantfileupload'),
        ),
    ]
