# Generated by Django 6.0.4 on 2026-05-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_campaign_coupons_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnNormalizedDataStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('internal_id', models.TextField(default='null')),
                ('user_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(default='male', max_length=20)),
                ('internal_order_id', models.TextField(default='null')),
                ('order_id', models.IntegerField()),
                ('order_date', models.DateField()),
                ('internal_product_id', models.TextField(default='null')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_link', models.URLField(blank=True, max_length=2000)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'unnormalized_data_staging',
                'managed': False,
            },
        ),
    ]
