# Generated by Django 6.0.4 on 2026-05-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_add_global_user_id_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='unnormalizeddata',
            name='hair_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unnormalizeddata',
            name='skin_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
