# Generated by Django 6.0.4 on 2026-05-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_unnormalizeddata_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unnormalizeddata',
            name='tag',
        ),
    ]
