# Generated by Django 6.0.4 on 2026-06-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_rename_campaign_attribute_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsUnNormalizedDataStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_product_id', models.TextField(default='null')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_category', models.CharField(max_length=100)),
                ('current_product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_link', models.URLField(blank=True, max_length=2000)),
                ('first_product_attribute', models.TextField(blank=True, null=True)),
                ('second_product_attribute', models.TextField(blank=True, null=True)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products_unnormalized_data_staging',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersUnNormalizedDataStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_user_id', models.TextField(default='null')),
                ('user_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, default='زن', null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('internal_order_id', models.TextField(default='null')),
                ('order_id', models.IntegerField()),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('internal_product_id', models.TextField(default='null')),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('then_product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_unnormalized_data_staging',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UnNormalizedDataStaging',
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='context',
            field=models.JSONField(blank=True, default=dict, help_text='Structured data relevant to this error'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='error_code',
            field=models.CharField(blank=True, help_text='Machine-readable error code, e.g. NO_COUPON_FOUND', max_length=100, null=True),
        ),
    ]
