# Generated by Django 6.0.4 on 2026-06-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_rename_campaign_attribute_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='customer_type',
            field=models.CharField(choices=[('همه', 'همه'), ('ویژه', 'ویژه'), ('فعال', 'فعال'), ('تازه وارد', 'تازه وارد'), ('در خطر ریزش', 'در خطر ریزش'), ('از دست رفته', 'از دست رفته')], default='همه', max_length=50),
        ),
    ]
