# Generated by Django 6.0.4 on 2026-07-03 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_alter_campaign_customer_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="product_source",
        ),
    ]
