# Generated by Django 6.0.4 on 2026-07-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_remove_campaign_product_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
