# Generated by Django 6.0.4 on 2026-07-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_sync_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupabaseOrder",
            fields=[
                ("order_id", models.TextField(primary_key=True, serialize=False)),
                ("order_date", models.DateField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("product_count", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "orders",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SupabaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.TextField()),
                ("quantity", models.IntegerField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("computed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "order_items",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SupabaseUser",
            fields=[
                ("user_id", models.TextField(primary_key=True, serialize=False)),
                ("phone_number", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("tenant_id", models.IntegerField(blank=True, default=5, null=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TriggerResult",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.IntegerField()),
                (
                    "rule_priority",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("detected_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("final_message", models.TextField(blank=True, null=True)),
                (
                    "processed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "hash",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("retry_count", models.IntegerField(blank=True, default=0, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("send_sms_date", models.DateField(blank=True, null=True)),
                ("is_selected", models.BooleanField(blank=True, null=True)),
                ("phone_number", models.TextField(blank=True, null=True)),
                ("sms_message_id", models.TextField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "trigger_results",
                "managed": False,
            },
        ),
        migrations.RenameIndex(
            model_name="syncconfig",
            new_name="core_syncco_api_key_e45f57_idx",
            old_name="core_syncco_api_key_ha_idx",
        ),
        migrations.RenameIndex(
            model_name="syncfieldmapping",
            new_name="core_syncfi_tenant__39f745_idx",
            old_name="core_syncfi_tenant__idx",
        ),
        migrations.RenameIndex(
            model_name="syncrun",
            new_name="core_syncru_tenant__8be5b9_idx",
            old_name="core_syncru_tenant__idx",
        ),
        migrations.RenameIndex(
            model_name="syncrun",
            new_name="core_syncru_status_92f3c7_idx",
            old_name="core_syncru_status_idx",
        ),
        migrations.RenameIndex(
            model_name="uploadjob",
            new_name="upload_job_tenant__cbbc12_idx",
            old_name="upload_job_tenant_status_idx",
        ),
        migrations.AlterField(
            model_name="syncconfig",
            name="api_key_prefix",
            field=models.CharField(
                blank=True,
                help_text="First 12 chars of the raw key, kept for display only (e.g. 'rsk_3f9a1c7b'). Never sufficient to authenticate.",
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="syncconfig",
            name="batch_size",
            field=models.PositiveIntegerField(
                default=1000,
                help_text="Max rows per POST from the ETL to the data ingest endpoints.",
            ),
        ),
        migrations.AlterField(
            model_name="syncconfig",
            name="is_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether the ETL is permitted to sync for this tenant. Set True only after تولید API has succeeded (i.e. a key exists and every required field mapping row is complete).",
            ),
        ),
        migrations.AlterField(
            model_name="syncfieldmapping",
            name="field_name",
            field=models.CharField(
                help_text="One of our canonical field names, see core/sync/field_registry.py",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="syncrun",
            name="failure_detail",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Precise machine detail, e.g. the exact missing table/column name. Not necessarily the same string shown to the end user.",
            ),
        ),
    ]
