# Generated by Django 6.0.4 on 2026-07-19 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0053_supabaseorder_supabaseorderitem_supabaseuser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="عنوان — shown in the notification list.",
                        max_length=255,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full body — shown when the tenant clicks مشاهده."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="خوانده شده (True) / خوانده نشده (False).",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant this notification is addressed to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_read"],
                        name="notificatio_tenant__67b689_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="notificatio_tenant__b302ab_idx",
                    ),
                ],
            },
        ),
    ]
